FROM debian:jessie

RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  systemd systemd-sysv sysv-rc sysvinit-utils
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  bash
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  bsdutils
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  passwd
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  netbase
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  diffutils
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  ncurses-base ncurses-bin
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  startpar
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  tzdata
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  sed
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  lsb-base
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  login
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  gzip
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  udev
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  mount
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  grep
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  dmsetup
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  base-passwd
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  util-linux
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libtext-charwidth-perl libtext-iconv-perl libtext-wrapi18n-perl
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libcryptsetup4
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libdevmapper1.02.1
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libsystemd0
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libgcrypt20
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libcomerr2
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  iproute2
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libsmartcols1
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libslang2
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libkmod2
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libmount1
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libblkid1
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libprocps3
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libudev1
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libustr-1.0-1
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  e2fslibs e2fsprogs
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libncurses5 libncursesw5
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libss2
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libcap2-bin
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  libgpg-error0
