FROM sillelien/jessy:master
RUN echo "Yes, do as I say!" | apt-get -y remove --force-yes  gnupg libreadline6 readline-common gpgv libapt-pkg4.12 libusb-0.1-4 libtinfo5 debian-archive-keyring

RUN rm -rf  /var/lib/dpkg
RUN rm -rf  /var/cache/* /usr/sbin/* /bin/systemd/*
RUN rm -rf  /usr/share/bash-completion /sbin/* /lib/udev

